### ISSUE TITLE
Please make wincertstore an optional dependency

### ISSUE THREAD

**Issue by n-a-sz** [DatastreamDSWS/Datastream#3]
The newly released DatastreamDSWS 1.0.1 now requires the wincertstore package, but it only runs on Windows. I guess Windows should not be a requirement for this package.
As we are using DatastreamDSWS on Linux, now we are forced to use version 1.0.0.

Please release a new version of DatastreamDSWS that has the wincertstore as an optional dependency, e.g. by handling import error when it is not available, something like this:

```python
try:
  import wincertstore
except ImportError:
  wincertstore = None
  logger.warning('Please install wincertstore if you need this feature.')

if wincertstore:
  # Using wincertstore
else:
  raise Exception('Please install wincertstore if you need this feature.')
```

**Comment by DatastreamDSWS** [comment]
Hi,

This has been done on version 1.0.6. please re-install this version and check.

**Comment by n-a-sz** [comment]
Thanks!
