### ISSUE TITLE
None Values

### ISSUE THREAD

**Issue by linusgvr** [DatastreamDSWS/Datastream#8]
Hi Team,

For me two Datastream Expression giving Trouble. i.e USREFAPT, PCH#(USREFAPT,1y), when I pass only these two I am getting Values; but if I pass with other symbols result is None.

DSR = DSDSWS.Datastream(username='Datastream_Username', password='Datastream_Password')

Tickers = 'USREFAPT, PCH#(USREFAPT,1y)'
Data = DSR.get_data(tickers=Tickers, fields=None, start='1950-01-01', freq='Q', kind=1)
-- Here I will get the Data

Tickers = 'USHOUSE.O-USPVH1UNE,PCH#(USHOUSE.O-USPVH1UNE,1y),USVACAPTR,USREFAPT,PCH#(USREFAPT,1y)'
Data = DSR.get_data(tickers=Tickers, fields=None, start='1950-01-01', freq='Q', kind=1)
But for USREFAPT, PCH#(USREFAPT,1y) Data is None

Please let me whats wrong with this?

**Comment by DatastreamDSWS** [comment]
Hi linusgvr,

Please see the details in the Readme Doc on how to 'Retrieve data for expressions'.

For above query:
Please use the below 'Tickers'. Note that there is '|E' which indicates that it is a expression.
Tickers = 'USHOUSE.O-USPVH1UNE,PCH#(USHOUSE.O-USPVH1UNE,1y),USVACAPTR,USREFAPT,PCH#(USREFAPT,1y)|E'

Thanks,
Vidya

**Comment by linusgvr** [comment]
Thanks, its fine now.

I have another issue: DSR.get_data(tickers='CQA#(WDPDEOIL)|E', fields=None, start='1970-01-01', freq='Q', kind=1) giving error as "$$ER: 1701, INVALID FREQUENCY Y"

**Comment by DatastreamDSWS** [comment]
Sunil

Please use our helpdesk to raise questions - https://my.refinitiv.com/content/mytr/en/helpandsupport.html

The issue is you are running a quarter average on annual series which isn’t possible

[cid:image001.png@01D67B89.E88A44C0]

Regards
Paul

**Comment by linusgvr** [comment]
Thanks
